### ISSUE TITLE
Loading Failure Callback & Backup Saving

### ISSUE THREAD

**Issue by Astecas** [BayatGames/SaveGameFree#10]
1. Hi! Are there any callbacks in cases where the loading process fails, like if there's a corrupted file which could not be decrypted or serialized correctly? (SaveGame.Exists() wont suit my needs this time).

2. It would be realy nice if there were an option for backup/versioning saving, where it could for example add a cycling index at the end of the ID. Then, if it failed to load using the last saved index, it would try loading a previous one. 

This backup system is what I'm trying to implement and the reason I need the failure callback btw, please let me know if there is another way to do so.

Thanks in advance!

**Comment by hasanbayatme** [comment]
You can use a try/catch block to check if the saving or loading process has failed, then you'd be able to run the next iteration through that, that callback would actually do the same, so I decided not to add that because a try/catch block is sufficient and more controllable.

And for the backup, you can implement that through a simple script by saving the data to multiple identifiers and then checking through if any are available.

Thank you!
