### ISSUE TITLE
Fast encryption?

### ISSUE THREAD

**Issue by ererbe** [BayatGames/SaveGameFree#4]
Is there anyway to do fast encryption (I dont need a zero go to a 100 char long code... 4 or something like this would be enough,,, becaues I need to save more than 200 files and this takes around 10 secounds (annoying) and loading also takes long...

would be nice if you can help me.

By the way this tool is awesome!

**Comment by hasanbayatme** [comment]
Hmm, I don't know any solution, because we are using almost all built-in feature provided by C#, so if you can improve the performance, you can take a look for ways on how to improve C# encryption performance, I suggest you to calculate the encryption and decryption type separately, and look which on is longer, I think the encryption is faster.
As far as I searched internet, I didn't found any resource for speeding up the encryption, so sorry, but give it a try, maybe I missed something.
Also, you can make your own encryption for Save Game Free as it allows you to provide an instance of the class for the encryptor.

I glad you like it, I do my best to help you.
Hope this helps.
Thanks.
